version: "3.7"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/root/
    environment:
      FLASK_ENV: development
  alphacep:
    image: "alphacep/kaldi-ru:latest"
    ports:
      - "2700:2700"